
name: 'iceberg_utils'
version: '1.1.2'

require-dbt-version: [">=1.3.0", "<3.0.0"]

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"
